# Generated by Django 4.2.8 on 2023-12-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='valid python', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
